import { PostReportItem } from '../types/reports'

export const handleReportData = (data: PostReportItem) => {
  const {
    month,
    year,
    sallaryS,
    sallaryB,
    restIncomeS,
    restIncomeB,
    percentageS,
    percentageB,
    commonCostS,
    commonCostB,
    individualCostS,
    individualCostB,
    savingsS,
    savingsB,
    comptPaymentS,
    comptPaymentB,
    monthTotalS,
    monthTotalB,
    prevDeptS,
    prevDeptB,
    payedS,
    payedB,
    restS,
    restB,
  } = data
  return [
    [
      month,
      year,
      sallaryS,
      sallaryB,
      restIncomeS,
      restIncomeB,
      percentageS,
      percentageB,
      commonCostS,
      commonCostB,
      individualCostS,
      individualCostB,
      savingsS,
      savingsB,
      comptPaymentS,
      comptPaymentB,
      monthTotalS,
      monthTotalB,
      prevDeptS,
      prevDeptB,
      payedS,
      payedB,
      restS,
      restB,
    ],
  ]
}
